export const MAX_POST_TITLE_LENGTH_IN_CHARS = 60;
export const MAX_POST_SUMMARY_LENGTH_IN_WORDS = 150;
export const DEFAULT_POST_SUMMARY_LENGTH_IN_WORDS = 100;
export const POST_LENGTH_WEIGHT = 20;
export const POST_LIKES_WEIGHT = 80;
